AWSTemplateFormatVersion: 2010-09-09
Description: >
  Kushal Sabharwal 24.07.2023
  Servers for deployment

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: ansiblenodes
      ImageId: ami-09538990a0c4fe9be 
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: CIServer
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0