---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC 
  hosts: targets 
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
   - setupNode
